name: serverpod_endpoints_generator
description: Endpoint generator for serverpod
version: 0.1.4


environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  generator_test: ^0.2.0
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
dependencies:
  analyzer: ^6.2.0
  build: ^2.4.1
  code_builder: ^4.6.0
  dart_style: ^2.3.3
  meta: ^1.10.0
  serverpod_endpoints_annotation: ^0.1.5
  source_gen: ^1.4.0

